-- adhel_airfields_from_sbre.sql
-- Gerado automaticamente a partir de aerodromos_dentro_SBRE.csv
-- Linhas: 777 | Gerado em: 2025-10-06T08:00:56

DO $mig$
BEGIN
  -- 1) Criação da tabela (se não existir)
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema='public' AND table_name='adhel_airfields'
  ) THEN
    CREATE TABLE public.adhel_airfields (
      id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tipo       text,
      oaci       text,
      ciad       text,
      name       text,
      municipio  text,
      uf         text NOT NULL CHECK (char_length(uf) = 2),
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now()
    );
  END IF;

    -- 4) Índices úteis
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='adhel_airfields_oaci_idx') THEN
    CREATE INDEX adhel_airfields_oaci_idx ON public.adhel_airfields (oaci);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='adhel_airfields_ciad_idx') THEN
    CREATE INDEX adhel_airfields_ciad_idx ON public.adhel_airfields (ciad);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='adhel_airfields_municipio_idx') THEN
    CREATE INDEX adhel_airfields_municipio_idx ON public.adhel_airfields (municipio);
  END IF;
END
$mig$;
